line-length = 88

[lint]
select = [
    "B",  # flake8-bugbear
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # Isort
    "Q",  # flake8-quotes
    "UP", # pyupgrade
    "W",  # pycodestyle warnings
]

[lint.per-file-ignores]
"**/migrations/**.py" = ["E501"]

[lint.isort]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
