# Generated by Django 6.0.6 on 2026-07-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puntovendita',
            options={'verbose_name_plural': 'Punti Vendita'},
        ),
    ]
